//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int ID { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string responsable { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha_Maxima_entrega_Factura { get; set; }
        public Nullable<System.DateTime> fecha_Maxima_realizacion { get; set; }
        public int ciudad_ID { get; set; }
        public int descripcion_producto_ID { get; set; }
        public int tipo_industria_ID { get; set; }
        public int forma_pago_ID { get; set; }
        public int flujo_ID { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual descripcion_producto descripcion_producto { get; set; }
        public virtual flujo flujo { get; set; }
        public virtual forma_pago forma_pago { get; set; }
        public virtual tipo_industria tipo_industria { get; set; }
    }
}
