//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class etapa_flujo
    {
        public int ID { get; set; }
        public string etapa { get; set; }
        public int flujo_ID { get; set; }
        public int flujoID { get; set; }
    
        public virtual flujo flujo { get; set; }
    }
}
