//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HELIX_ETAPA_FLUJO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HELIX_ETAPA_FLUJO()
        {
            this.HELIX_TICKET = new HashSet<HELIX_TICKET>();
        }
    
        public int ID_ETAPAFLUJO { get; set; }
        public Nullable<int> ID_FLUJO { get; set; }
        public string DESCRIPCION_ETAPA { get; set; }
        public string NOMBRE_ETAPA { get; set; }
    
        public virtual HELIX_FLUJO HELIX_FLUJO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HELIX_TICKET> HELIX_TICKET { get; set; }
    }
}
