//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HELIX_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HELIX_USUARIO()
        {
            this.HELIX_TICKET = new HashSet<HELIX_TICKET>();
        }
    
        public int ID_USUARIO { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public string MAIL { get; set; }
        public string TELEFONO { get; set; }
        public string CARGO { get; set; }
    
        public virtual HELIX_ROL HELIX_ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HELIX_TICKET> HELIX_TICKET { get; set; }
    }
}
