//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HELIX_TIPO_INDUSTRIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HELIX_TIPO_INDUSTRIA()
        {
            this.HELIX_CLIENTE = new HashSet<HELIX_CLIENTE>();
        }
    
        public int ID_TIPOINDUSTRIA { get; set; }
        public string TIPO_INDUSTRIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HELIX_CLIENTE> HELIX_CLIENTE { get; set; }
    }
}
