//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix2._0.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelixEntities : DbContext
    {
        public HelixEntities()
            : base("name=HelixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HELIX_CIUDAD> HELIX_CIUDAD { get; set; }
        public virtual DbSet<HELIX_CLIENTE> HELIX_CLIENTE { get; set; }
        public virtual DbSet<HELIX_COMENTARIO> HELIX_COMENTARIO { get; set; }
        public virtual DbSet<HELIX_ETAPA_FLUJO> HELIX_ETAPA_FLUJO { get; set; }
        public virtual DbSet<HELIX_FLUJO> HELIX_FLUJO { get; set; }
        public virtual DbSet<HELIX_FORMA_PAGO> HELIX_FORMA_PAGO { get; set; }
        public virtual DbSet<HELIX_ROL> HELIX_ROL { get; set; }
        public virtual DbSet<HELIX_TICKET> HELIX_TICKET { get; set; }
        public virtual DbSet<HELIX_TIPO_INDUSTRIA> HELIX_TIPO_INDUSTRIA { get; set; }
        public virtual DbSet<HELIX_USUARIO> HELIX_USUARIO { get; set; }
    }
}
