//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HELIX_COMENTARIO
    {
        public Nullable<int> ID_CLIENTE { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_TICKET { get; set; }
        public int ID_COMENTARIO { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<System.DateTime> FECHA_COMENTARIO { get; set; }
    
        public virtual HELIX_TICKET HELIX_TICKET { get; set; }
    }
}
