//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix2._0.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelixEntities : DbContext
    {
        public HelixEntities()
            : base("name=HelixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<comentario> comentario { get; set; }
        public virtual DbSet<descripcion_producto> descripcion_producto { get; set; }
        public virtual DbSet<etapa_flujo> etapa_flujo { get; set; }
        public virtual DbSet<flujo> flujo { get; set; }
        public virtual DbSet<forma_pago> forma_pago { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<tipo_industria> tipo_industria { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
